### ISSUE TITLE
Cannot build, some /dist files must be included

### ISSUE THREAD

**Issue by PascalCoinDev** [bitcoinerlab/web#1]
`/dist` folder is not updated due included in `.gitignore` but some files are needed to build
See file `/src/modules/index.js`:
```
import explorerReadme from "../../dist/public/docs/explorer/README.md";
import discoveryReadme from "../../dist/public/docs/discovery/README.md";
import descriptorsReadme from "../../dist/public/docs/descriptors/README.md";
```

Those `README.md` files are not included

**Comment by landabaso** [comment]
Hey Albert!

The structure assumes that you have a parent folder with all the libraries from the bitcoinerlab family installed in the following manner:

```
<parentFolder>/web
<parentFolder>/discovery
<parentFolder>/explorer
<parentFolder>/descriptors
<parentFolder>/miniscript
```

To generate the necessary files you mentioned, you'd run the command `npm run webdocs`. If you prefer a different folder structure, you'll need to adjust the `build-docs.sh` script accordingly.

As these sources pertain to the webpage for bitcoinerlab.com, I hadn't included any build or usage instructions. I honestly didn't anticipate anyone else trying to build it besides me. 😅

**Comment by landabaso** [comment]
I acknowledge that it's somewhat unconventional for `src` to depend on `dist`. It's a bit of a chicken-and-egg situation because those READMEs are indeed "built" /copied and must be distributed (and therefore should be in `dist`), yet they're also required in `src`.

However, I wouldn't overcomplicate this since it's specifically for the website and not intended for general public use.
